apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgBv6xFOO1pUEgz5/tCjGFQtUc6tRjxlWyBoZO4UOMY2plfjnfbLCiBBvgu3B6qksbfz/N3eLWqQmFXh+W9py3kqH+1O8Q0SiJmE/1AAh1Rf9M2YfbFejE84UzibBaLiUTdWx0//pAqcv8w8euUJwONvaaH4ejwb7bye1QHbnx64eJs94d0K69n5bzMR1zxJ9pf/4Iai2U23qu3RSsFD6o9hsW8hQqZkGN+SMWv49x5snGZ4IlmbQtN5WB7B2mS6I85KpBN3l4JF3RkhF8ZbMVMkdJfK5FElpHpbUtl3U2kbb1i3cDOAKKrndPgwpZu88E8N8tx/6RldxDb4LtBRlNfZut8U5h67It99185RWAlH+ecOlTg6c8dO9GXCE5gvjxZ16/sltxLj8rVjmbjMu+BCWHUW7kFgTigynTUUbFbUTE6Aq82/8YzT7ba4tiDXRDdeWlRNW4A8XHdSiSqRaNt8nYWNBu5uXU8AhFLXdy+PJRVx9jYPpRuwppPlAMt1DQtEurqqnQky1GSHYX1mhxu1Qg7IQftT8III/byN2eYpwsWakn53DuVqsvef3cYCytrLqq7x7Gm68hw+aWmoWKHO4PaozN4A4EDwrscDhU44XbD4O1VenbEts0w98l/eqHrDkiC6qXry+WaoyfYm+MfaC9FX3zJS//ZGRSxI3AwFTjHLl5EEY+PCO4RkXPT0uKCnPSZt+X52N5Cu/j268Yp6nyJHSgr6jI0B
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

