apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:4QyYO84kgMbaootVigHXcB6pjWdqDCQVTQ==,iv:zgI2swW5wrOglfcUNYcDU8d0EnGV9oNOyzHQhzgr8WM=,tag:VGGvptlZZbSwXP5yTKo0+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-20T02:53:56Z"
    mac: ENC[AES256_GCM,data:avY3DY2mG0yrIMcnCEbKZIgW3aRfdfVWHwRzPlH789yvLbeWOxDkS97VySWY3NNvfeGqVY1sWhN5v3uN9LCAaCt/ZMD5fRvbFdFytpEYOMfr2i1YRwD7R4EZd6X//zJF8Pv9xd8WlNc//fCuOdMAAhSPuIa90aWSvDIOhijqD0E=,iv:MA/8lecv+3KGyFdT8es+ttbR7sGHXttUBYpz2ZakhGo=,tag:XzuGuCawFp7BbFBiEohSew==,type:str]
    pgp:
        - created_at: "2025-04-20T02:53:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAwjHzuQNmp/RAQv9Eco6wmAoChWhPZmY3a+bRJtPvmF9UXcTHaJAEOw5r7ja
            Q7zQZ20RTXF8UF83Kl2p0LqemVxI2IqDeHjPdzSIxQl1/TVbumNir+ObMTBr2XDr
            w0sG7UQrTMug+RD6a/eqSaoqywREEgl/HdVWSbw0BniWYiwY912qC12GRyzsHmHA
            /Ive0RgsD0nAhwQfy5ZaYMXXHZdQdgXAl0GHM12fQgqd0Gh4rnch95Wqispu6k+D
            gEiI8cUODPYJ6AHlx3tZ1iw3kCkGTN3BUKcvleTlV0oCbplT01e3xF29rCbLuCaL
            TcGKmtgyJ4Dw+R0BvJpwz/FQX5UaZKBmKPTLHIiaBkEVpsYjk+M35MPxdos40Q6Q
            BXg08v4xA8SRFbTJLX6kSgE2+GXqZYdV3lHOeB7HxeT4OZa3PtOcLUeyZtZbXw73
            ES7nrJxnUGRXKPWNM791VBDnqSoorgQVNmGSL+7jiZyE5Mxhc8msl6vmu5l9pLok
            XxaURY5YF8dSnL5PJsf61GYBCQIQkJ4jm6SxBTihjvLDPobeHdUTXFN4Em420WWj
            sNMJCFCuX+EsFxXN1/xlSQX52b/bVpUXTTk4dAX9AuGkRgxGj4g1/aNlxP1Se5hI
            gDnJkvB0ZhqVcQUeJgNNjTUAL93Cmfo=
            =0mdC
            -----END PGP MESSAGE-----
          fp: 569C49931F5832E8CD54C99E9CC750AB38FA66E3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
